blog/urls.py
from django.conf.urls import url
from .views import post_list,\
    PostList,PostCreate,\
    PostUpdate,PostDelete,\
    PostArchiveYear,PostArchiveMonth,PostDetail

urlpatterns=[
    url(r'^$',
        PostList.as_view(template_name='blog/post_list.html'),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
      url(r'^(?P<year>\d{4})/'
          r'(?P<month>\d{1,2})/'
          r'(?P<slug>[\w\-]+)/'
          r'delete/$',
          PostDelete.as_view(),
          name='blog_post_delete'),
]

bloguser/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView,TemplateView
from django.core.urlresolvers import reverse_lazy
from .views import (DisableAccount,ActivateAccount\
    ,CreateAccount,ResendActivationEmail)

password_urls=[
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'bloguser/user_create_done.html')),
        name='create_done'),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'bloguser/password_reset_complete.html',
         'extra_context':
             {'form':AuthenticationForm}},
        name='pw_reset_complete'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'bloguser/password_reset_confirm.html',
         'post_reset_redirect':reverse_lazy(
             'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'bloguser/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'bloguser/password_reset_form.html',
         'email_template_name':
            'bloguser/password_reset_email.txt',
         'subject_template_name':
            'bloguser/password_reset_subject.txt',
         'post_reset_redirect':reverse_lazy(
             'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':'bloguser/password_change_form.html',
         'post_change_redirect':reverse_lazy(
             'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
         'bloguser/password_change_done.html'},
        name='pw_change_done'),
]

urlpatterns=[
    url(r'^password/',include(password_urls)),
    url(r'^$',RedirectView.as_view(
        pattern_name='dj-auth:login',
        permanent=False)),
    url(r'^login/$',
        auth_views.login,
        {'template_name':'bloguser/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name':'bloguser/logged_out.html',
         'extra_context':
             {'form':AuthenticationForm}},
        name='logout'),
]

suorganizer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include,url
from django.contrib import admin
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from blog.views import PostList
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from django.views.generic import RedirectView,TemplateView
from django.contrib.auth import urls as auth_urls
from bloguser import urls as user_urls


urlpatterns = [
    url(r'^$',RedirectView.as_view(
        pattern_name='blog_post_list',
        permanent=False)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(blog_urls)),
    url(r'^contact/',include(contact_urls)),
    url(r'^startup/',include(startup_urls)),
    url(r'^tag/',include(tag_urls)),
    url(r'^user/',include(user_urls,
                          app_name='bloguser',
                          namespace='dj-auth')),
    # url(r'^$',homepage),
    # url(r'^tag/(?P<slug>[\w\-]+)/$',
    #     tag_detail,name='organizer_tag_detail'),
]

bloguser/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

bloguser/forms.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from .utils import ActivationMailFormMixin
from django.contrib.auth import get_user_model
import logging
from django import forms

logger=logging.getLogger(__name__)

class ResendActivationEmailForm(
            ActivationMailFormMixin,forms.Form):
    email=forms.EmailField()
    mail_validation_error = (
        'Could not re-send activation email '
        'Please try again later.Sorry')

    def save(self,**kwargs):
        User=get_user_model()
        try:
            user=User.objects.get(
                email=self.cleaned_data['email'])
        except:
            logger.warning(
                'Resend Activation: No user with '
                'email:{}.'.format(
                    self.cleaned_data['email']))
            return None
        self.send_mail(user=user,**kwargs)
        return user

class UserCreationForm(ActivationMailFormMixin,
                       BaseUserCreationForm):

    mail_validation_error=(
        'User created. Could not send activation '
        'email. Please try again later (Sorry!)')

    class Meta(BaseUserCreationForm.Meta):
        model=get_user_model()
        fields=('username','email')

    def save(self,**kwargs):
        user=super().save(commit=False)
        if not user.pk:
            user.is_active=False
            send_mail=True
        else:
            send_mail=False
        user.save()
        self.save_m2m()
        if send_mail:
            self.send_mail(user=user, **kwargs)
        return user

bloguser/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import get_user, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from .utils import MailContextViewMixin
from .forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.messages import error,success
from django.views.decorators.cache import never_cache
from django.contrib.auth import \
    (get_user,get_user_model,logout)
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator as token_generator
from .forms import ResendActivationEmailForm,UserCreationForm


class ResendActivationEmail(
        MailContextViewMixin,View):

    form_class=ResendActivationEmailForm
    success_url=reverse_lazy('dj-auth:login')
    template_name='bloguser/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self,request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    def post(self,request):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            user=bound_form.save(
                **self.get_save_kwargs(request))
            if(user is not None
                    and not bound_form.mail_sent):
                errs=(
                    bound_form.non_field_errors())
                for err in errs:
                    error(request,err)
                if errs:
                    bound_form.errors.pop(
                        '__all__')
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form':bound_form})

        success(
            request,
            'Activation Email Sent!')
        return redirect(self.success_url)

class ActivateAccount(View):
    success_url=reverse_lazy('dj-auth:login')
    template_name='bloguser/user_activate.html'

    @method_decorator(never_cache)
    def get(self,request,uidb64,token):
        User=get_user_model()
        try:
            uid=force_text(
                urlsafe_base64_decode(uidb64))
            user=User.objects.get(pk=uid)
        except(TypeError,ValueError,OverflowError,
               User.DoesNotExist):
            user=None

        if(user is not None
            and token_generator.check_token(user,token)):
            user.is_active=True
            user.save()
            success(
                request,
                'User Activated! '
                'You may now login.')
            return redirect(self.success_url)
        else:
            return TemplateResponse(
                request,
                self.template_name)


class CreateAccount(MailContextViewMixin, View):
    form_class=UserCreationForm
    success_url=reverse_lazy(
        'dj-auth:create_done')
    template_name='bloguser/user_create.html'

    @method_decorator(csrf_protect)
    def get(self,request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters(
        'password1','password2'))
    def post(self,request):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(
                **self.get_save_kwargs(request))
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else:
                errs=(
                    bound_form.non_field_errors())
                for err in errs:
                    error(request,err)
                return redirect('dj-auth:resend-activation')

        return TemplateResponse(
            request,
            self.template_name,
            {'form':bound_form})

class DisableAccount(View):
    success_url=settings.LOGIN_REDIRECT_URL
    template_name=(
        'bloguser/user_confirm_delete.html')

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self,request):
        return TemplateResponse(
            request,
            self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self,request):
        user=get_user(request)
        user.set_unusable_password()
        user.is_active=False
        user.save()
        logout(request)
        return redirect(self.success_url)

bloguser/templates/bloguser/base_user.html
{% extends parent_template|default:"base.html" %}

bloguser/templates/bloguser/logged_out.html
{% extends parent_template|default:"bloguser/base_user.html" %}
{% block title %}
{{ block.super }} - Logged Out
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>You've successfully logged out.</p>
        {% include "bloguser/login_form.html" with login_button='Log Back In' %}
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/login.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Login
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two five columns">
        {% include "bloguser/login_form.html" %}
    </div>
    <div class="three columns">
        <ul class="task-list">
            <li><a href="{% url 'dj-auth:create' %}">
                Register New Account</a></li>
            <li><a href="{% url 'dj-auth:pw_reset_start' %}">
                Forgotten password?</a></li>
            <li><a href="{% url 'dj-auth:resend_activation' %}">
                Lost Activation E-Mail?</a></li>
        </ul>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/login_form.html
<form action="{% url 'dj-auth:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
    {% endif %}

    <button type="submit">
        {{ login_button|default:'Log in' }}
    </button>
</form>

bloguser/templates/bloguser/password_change_done.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>Password successfully changed.</p>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/password_change_form.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <form action="{% url 'dj-auth:pw_change' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Change Password
            </button>
        </form>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/password_reset_complete.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Password Reset Successful
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>Your password has been reset.</p>
        <p>Log in below using your new password.</p>
        {% include "bloguser/login_form.html" %}
    </div>
</div>

bloguser/templates/bloguser/password_reset_confirm.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            {% if validlink %}
                <p>Enter a new password below.</p>
                <form action="{{ request.path }}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="button-primary" type="submit">
                        Save New Password</button>
                </form>
            {% else %}
                <p>This reset link is no longer valid.</p>
                <p>Please request a new reset email
                <a href="{% url 'dj-auth:pw_reset_start' %}">
                    here
                </a>.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

bloguser/templates/bloguser/password_reset_form.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <div class="center">
                <p>Reset your password by email.</p>
            </div>
            <form action="{% url 'dj-auth:pw_reset_start' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Send Me Reset Instructions
                </button>
            </form>
        </div>
    </div>
{% endblock %}

bloguser/templates/bloguser/password_reset_sent.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>Password reset email sent!</p>
        <p>Please check your inbox and spam box.</p>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/resend_activation.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Resend Activation E-Mail
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <div class="center">
        <p>Resend your account activation email.</p>
      </div>
      <form
          action="{% url 'dj-auth:resend_activation' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Resend Activation E-Mail</button>
      </form>
  </div></div>
{% endblock %}

bloguser/templates/bloguser/user_confirm_delete.html
{% extends parent_template|default:"bloguser/base_user.html" %}
{% block title %}
{{ block.super }} - Disable Account
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>Disable your account?</p>
        <p>This cannot be undone.</p>
        <form action="{% url 'dj-auth:disable' %}" method="post">
            {% csrf_token %}
            <button type="submit">
                Disable Account
            </button>
        </form>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/user_create.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Create Account
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <div class="center">
            <a href="{% url 'dj-auth:resend_activation' %}">
                Lost Activation E-Mail?</a>
        </div>
        <form action="{% url 'dj-auth:create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create New Account
            </button>
        </form>
    </div>
</div>
{% endblock %}

bloguser/templates/bloguser/user_create_done.html
{% extends parent_template|default:"bloguser/base_user.html" %}

{% block title %}
{{ block.super }} - Account Created
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>Your account has been created</p>
        <p>Please check your email for the activation link</p>
    </div>
</div>
{% endblock %}