blog/urls.py
from django.conf.urls import url
from .views import post_list,\
    PostList,PostCreate,\
    PostUpdate,PostDelete,\
    PostArchiveYear,PostArchiveMonth,PostDetail

urlpatterns=[
    url(r'^$',
        PostList.as_view(template_name='blog/post_list.html'),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
      url(r'^(?P<year>\d{4})/'
          r'(?P<month>\d{1,2})/'
          r'(?P<slug>[\w\-]+)/'
          r'delete/$',
          PostDelete.as_view(),
          name='blog_post_delete'),
]

organizer/urls.py
from django.conf.urls import url
from .views import startup_detail,\
    startup_list,tag_detail,tag_list,tag_create,\
    TagCreate,TagUpdate,StartupCreate,StartupDelete,NewsLinkCreate,TagDelete,StartupUpdate,NewsLinkUpdate,NewsLinkDelete

urlpatterns=[

]

suorganizer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include,url
from django.contrib import admin
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from blog.views import PostList
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from django.views.generic import RedirectView,TemplateView
from django.contrib.auth import urls as auth_urls
from bloguser import urls as user_urls


urlpatterns = [
    url(r'^$',RedirectView.as_view(
        pattern_name='blog_post_list',
        permanent=False)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(blog_urls)),
    url(r'^contact/',include(contact_urls)),
    url(r'^startup/',include(startup_urls)),
    url(r'^tag/',include(tag_urls)),
    url(r'^user/',include(user_urls,
                          app_name='bloguser',
                          namespace='dj-auth')),
    # url(r'^$',homepage),
    # url(r'^tag/(?P<slug>[\w\-]+)/$',
    #     tag_detail,name='organizer_tag_detail'),
]

organizer/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from datetime import date

class Tag(models.Model):
    name=models.CharField(max_length=31,unique=True)
    slug=models.SlugField(max_length=31,unique=True,
                          help_text='A label for URL config')
    def __str__(self):
        return  self.name
    class Meta:
        ordering=['name']
    def get_absolute_url(self):
        return reverse('organizer_tag_detail',
                       kwargs={'slug':self.slug})
    def get_update_url(self):
        return reverse('organizer_tag_update',
                       kwargs={'slug':self.slug})
    def get_delete_url(self):
        return reverse('organizer_tag_delete',
                       kwargs={'slug':self.slug})
    def published_posts(self):
        return self.blog_posts.filter(
            pub_date__lt=date.today())

class Startup(models.Model):
    name = models.CharField(max_length=31,db_index=True)
    slug = models.SlugField(max_length=31,
                            unique=True,
                            help_text='A label for URL config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags=models.ManyToManyField(Tag,blank=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering=['name']
        get_latest_by='founded_date'
    def get_absolute_url(self):
        return reverse('organizer_startup_detail',
                       kwargs={'slug':self.slug})
    def get_update_url(self):
        return reverse('organizer_startup_update',
                       kwargs={'slug':self.slug})
    def get_delete_url(self):
        return reverse(
            'organizer_startup_delete',
            kwargs={'slug':self.slug})
    def get_newslink_create_url(self):
        return reverse(
            'organizer_newslink_create',
            kwargs={'startup_slug':self.slug})
    def published_posts(self):
        return self.blog_posts.filter(
            pub_date__lt=date.today())



class NewsLink(models.Model):
    title=models.CharField(max_length=63)
    pub_date=models.DateField('date published')
    link=models.URLField(max_length=255)
    startup=models.ForeignKey(Startup)
    slug=models.SlugField(max_length=63)

    def __str__(self):
        return "{}:{}".format(self.startup,self.title)

    class Meta:
        verbose_name='news_article'
        ordering=['-pub_date']
        get_latest_by='pub_date'
        unique_together=('slug','startup')

    def get_absolute_url(self):
        return self.startup.get_absolute_url()
    def get_update_url(self):
        return reverse(
            'organizer_newslink_update',
            kwargs={
                    'startup_slug':self.startup.slug,
                    'newslink_slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer_newslink_delete',
                       kwargs={
                           'startup_slug':self.startup.slug,
                           'newslink_slug':self.slug})

organizer/forms.py
from django import forms
from .models import Tag,NewsLink,Startup
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput


class SlugCleanMixin:
    def clean_slug(self):
        new_slug=self.cleaned_data['slug'].lower()
        if new_slug=='create':
            raise ValidationError('Slug may not be create')
        return new_slug


class NewsLinkForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model=NewsLink
        fields= '__all__'
        widgets={'startup':HiddenInput()}

 #       exclude=('startup',)

    # def save(self,**kwargs):
    #     startup_obj=kwargs.get('startup_obj',None)
    #     if startup_obj is not None:
    #         instance=super().save(commit=False)
    #         instance.startup=startup_obj
    #         instance.save()
    #         self.save_m2m()
    #     else:
    #         instance=super().save()
    #     return instance
    # def clean(self):
    #     cleaned_data=super().clean()
    #     slug=cleaned_data.get('slug')
    #     startup_obj=self.data.get('startup')
    #     exists=(
    #         NewsLink.objects.filter(
    #             slug__iexact=slug,
    #             startup=startup_obj,
    #         ).exists())
    #     if exists:
    #         raise ValidationError(
    #             "News articles with this Slug and Startup"
    #             " already exists.")
    #     else:
    #         instance=super().save()
    #         return cleaned_data
    # def save(self,**kwargs):
    #     instance=super().save(commit=False)
    #     instance.startup=(
    #         self.data.get('startup'))
    #     instance.save()
    #     self.save_m2m()
    #     return instance

class StartupForm(SlugCleanMixin,forms.ModelForm):
    class Meta:
        model=Startup
        fields='__all__'


class TagForm(SlugCleanMixin,forms.ModelForm):
    class Meta:
        model=Tag
        fields=['name','slug']

    def clean_name(self):
        return self.cleaned_data['name'].lower()
    def save(self):
        new_tag=Tag.objects.create(
            name=self.cleaned_data['name'],
            slug=self.cleaned_data['slug'])
        return new_tag

organizer/views.py
from django.shortcuts import render
from .models import Startup,Tag,NewsLink
from django.shortcuts import get_object_or_404,redirect,render_to_response,render
from .forms import TagForm,StartupForm,NewsLinkForm
from django.views.generic import \
    (CreateView,DeleteView,
     DetailView,View,ListView)
from django.core.urlresolvers import reverse,reverse_lazy
from django.core.paginator import (
    EmptyPage,PageNotAnInteger,Paginator)
from core.utils import UpdateView
from .utils import PageLinksMixin,\
    StartupContextMixin,NewsLinkGetObjectMixin
from django.contrib.auth.decorators import login_required,\
    permission_required,user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth import PermissionDenied
from bloguser.decorators import \
    class_login_required,require_authenticated_permission

@require_authenticated_permission(
    'organizer.delete_newslink')
class NewsLinkDelete(StartupContextMixin,
                     DeleteView):
    model=NewsLink
    slug_url_kwarg='newslink_slug'

    def get_success_url(self):
        return (self.object.startup.get_absolute_url())

@require_authenticated_permission(
    'organizer.change_newslink')
class NewsLinkUpdate(NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     UpdateView):
    form_class=NewsLinkForm
    model=NewsLink
    slug_url_kwarg='newslink_slug'

@require_authenticated_permission(
    'organizer.add_newslink')
class NewsLinkCreate(NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     CreateView):
    form_class=NewsLinkForm
    model=NewsLink

    def get_initial(self):
        startup_slug=self.kwargs.get(
            self.startup_slug_url_kwarg)
        self.startup=get_object_or_404(
            Startup,slug__iexact=startup_slug)
        initial={
            self.startup_context_object_name:
                self.startup,
        }
        initial.update(self.initial)
        return initial

@require_authenticated_permission(
    'organizer.add_startup')
class StartupCreate(CreateView):
    form_class=StartupForm
    model=Startup


class StartupDetail(DetailView):
    model=Startup

class StartupList(PageLinksMixin,ListView):
    model=Startup
    paginate_by=5

@require_authenticated_permission(
    'organizer.change_startup')
class StartupUpdate(UpdateView):
    form_class = StartupForm
    model=Startup

@require_authenticated_permission(
    'organizer.delete_startup')
class StartupDelete(DeleteView):
    model=Startup
    success_url = reverse_lazy('organizer_startup_list')

def startup_list(request):
    return render(
        request,
        'organizer/startup_list.html',
        {'startup_list':Startup.objects.all()})


class TagDetail(DetailView):
    model=Tag


class TagList(PageLinksMixin,ListView):
    paginate_by = 5
    model=Tag

def in_contrib_group(user):
    if user.groups.filter(
        name='contributors').exists():
        return True
    else:
        raise PermissionDenied

@require_authenticated_permission(
    'organizer.add_tag')
class TagCreate(CreateView):
    form_class=TagForm
    model=Tag

@require_authenticated_permission(
    'organizer.change_tag')
class TagUpdate(UpdateView):
    form_class=TagForm
    model=Tag

@require_authenticated_permission(
    'organizer.delete_tag')
class TagDelete(DeleteView):
    model=Tag
    success_url = reverse_lazy('organizer_tag_list')

def tag_create(request):
    if request.method=='POST':
        form=TagForm(request.POST)
        if form.is_valid():
            new_tag=form.save()
            return redirect(new_tag)
    else:
        form=TagForm()
    return render(
        request,
        'organizer/tag_form.html',
        {'form':form})


def model_list(request,model):
    context_object_name='{}_list'.format(model._meta.model_name)
    context={
        context_object_name:model.objects.all(),
    }
    template_name=(
        'organizer/{}_list.html'.format(
            model._meta.model_name))

    return render(request,template_name,context)

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

{% block content %}
<div class="row">
    <section class="eight columns">
        {% block org_content %}
        This is default content!
        {% endblock %}
    </section>
    <section class="desktop four columns">
        {% block create_button %}{% endblock %}
    </section>
</div>

{% if is_paginated %}
<div class="row">
    <div class="twelve columns">
       <ul class="pagination">
            {% if first_page_url %}
            <li>
                <a href="{{ first_page_url }}">
                    First</a>
            </li>
            {% endif %}
            {% if previous_page_url %}
           <li>
               <a href="{{ previous_page_url }}">Previous</a>
           </li>
           {% endif %}
            <li>
                Page {{ page_obj.number }}
                of {{ paginator.num_pages }}
            </li>
            {% if next_page_url %}
            <li>
                <a href="{{ next_page_url }}">
                    Next
                </a>
            </li>
            {% endif %}
        `   {% if last_page_url %}
                <li>
                    <a href="{{ last_page_url }}">
                        Last</a>
                </li>
           {% endif %}
       </ul>
    </div>
</div>
{% endif %}
{% endblock %}

organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - NewsLink Confirm Delete
{% endblock %}

{% block content%}
<div class="row">
    <div class="offset-by-two eight columns">
        <form action="{{ newslink.get_delete_url }}"
              method="post">
            <p>
                Are you sure you want to delete link to article {{ newslink.name }}?
            </p>
            <a href="{{ newslink.get_absolute_url }}" class="button button-primary">
                Cancel
            </a>
            <button type="submit">
                Delete Article Link
            </button>
        </form>
    </div>
</div>
{% endblock %}

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ startup.get_newslink_create_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button button-primary" type="submit">
          Link Article</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - NewsLink Update
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <form action="{{ newslink.get_update_url }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button button-primary"
                    type="submit">
                Update Article Link
            </button>
        </form>
    </div>
</div>
{% endblock %}

organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startup Confirm Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <form action="{{ startup.get_delete_url }}" method="post">
            {% csrf_token %}
            <p>
                Are you sure you want to delete startup {{ startup.name }}?
            </p>
            <a href="{{ startup.get_absolute_url }}"
               class="button button-primary">
                Cancel
            </a>
            <button type="submit">Delete Startup</button>
        </form>
    </div>
</div>
{% endblock %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startup Detail
{% endblock %}

{% block content %}
<article>

    <div class="row">
        <div class="offset-by-two eight columns">

  <h2>{{ startup.name }}</h2>
    {% if perms.organizer.change_startup or perms.organizer.delete_startup %}
    <ul class="inline">
        {% if perms.organizer.change_startup %}
        <li>
            <a href="{{ startup.get_update_url }}" class="button">
                Edit Startup
            </a>
        </li>
        {% endif %}
        {% if perms.organizer.delete_startup %}
        <li>
            <a href="{{ startup.get_delete_url }}" class="button">
                Delete Startup
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}

  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

      <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  <p>{{ startup.description|linebreaks }}</p>
    </div>
</div><!--row-->

{% if startup.newslink_set.all or perms.blog.view_future_post and startup.blog_posts.all or startup.published_posts|length > 0 or perms.organizer.add_newslink %}
<div class="row">
        {% if startup.newslink_set.all %}
            <section>
          {% if perms.blog.view_future_post and startup.blog_posts.all or startup.published_posts|length > 0 %}
              <section class="meta offset-by-two one-third column">
          {% else %}
              <section class="meta offset-by-two two-thirds-column">
          {% endif %}

            <h3>Recent News</h3>
            {% if perms.organizer.add_newslink %}
          <p>
              <a href="{{ startup.get_newslink_create_url }}"
              class="button">
                  Add Article</a></p>
            {% endif %}
            <ul>
              {% for newslink in startup.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">
                    {{ newslink.title|title }}</a>
                    {% if perms.organizer.change_newslink or perms.organizer.delete_newslink %}
                    <ul class="inline">
                        {% if perms.organizer.change_newslink %}
                        <li>
                            <a href="{{ newslink.get_update_url }}"
                            class="button">
                                Edit Link</a></li>
                        {% endif %}
                        {% if perms.organizer.delete_newslink %}
                        <li>
                            <a href="{{ newslink.get_delete_url }}"
                            class="button">
                                Delete Link</a></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </li>
              {% endfor %}
            </ul>
          </section>
            {% elif perms.organizer.add_newslink %}
            {% if perms.blog.view_future_post and startup.blog_posts.all or startup.published_posts > 0 %}
                <section class="meta offset-by-two one-third column">
            {% else %}
                <section class="meta offset-by-two two-thirds column">
            {% endif %}

            <p>
                <a href="{{ startup.get_newslink_create_url }}" class="button">
                    Add Article</a></p>
            </section>
      {% endif %}

        {% if perms.blog.view_future_post and startup.blog_posts.all or startup.published_posts|length > 0 %}
            {% if startup.newslink_set.all or perms.organizer.add_newslink%}
            <section class="meta one-third column">
            {% else %}
            <section class="meta offset-by-two two-thirds column">
            {% endif %}

            {% if perms.blog.view_future_post and startup.blog_posts.all %}
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
              {% for post in startup.blog_posts.all %}
                <li>
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
            {% elif startup.published_posts|length > 0 %}
                <h3>Blog Post{{ startup.published_posts|pluralize }}</h3>
                <ul>
                {% for post in startup.published_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title|title }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
                {% endif %}
          </section>
      {% endif %}
</div>
{% endif %}

</article>
{% endblock %}

organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{% url 'organizer_startup_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startup Update
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight-columns">
        <form action="{{ startup.get_update_url }}"
              method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button-primary" type="submit">
                Update Startup
            </button>
        </form>
    </div>
</div>
{% endblock %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{#{% block content %}#}

{% block create_button %}
    {% if perms.organizer.add_startup %}
    <a href="{% url 'organizer_startup_create' %}"
       class="button button-primary">
        Create New Startup
    </a>
    {% endif %}
{% endblock %}

{% block org_content %}
<h2>Startup List</h2>
    {% if perms.organizer.add_startup %}
    <div class="mobile">
        <a href="{% url 'organizer_startup_create' %}"
        class="button button-primary">
            Create New Startup</a>
    </div>
    {% endif %}
<ul>
    {% for startup in startup_list %}
    <li>
        <a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}</a>
        {% if perms.organizer.change_startup or perms.organizer.delete_startup %}
    <ul class="inline">
        {% if perms.organizer.change_startup %}
        <li>
            <a href="{{ startup.get_update_url }}"
            class="button">
                Edit Startup</a></li>
        {% endif %}
        {% if perms.organizer.delete_startup %}
        <li>
            <a href="{{ startup.get_delete_url }}"
            class="button">
                Delete Startup
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    </li>
    {% empty %}
    <li><em>No Startups Available</em></li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ tag.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ tag.name }}?
        </p>
        <a href="{{ tag.get_absolute_url }}"
        class="button button-primary">
          Cancel</a>
        <button type="submit">Delete Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block org_content %}
 <h2> {{ tag.name|title }} </h2>
    {% if perms.organizer.change_tag or perms.organizer.delete_tag %}
    <ul class="inline">
    {% if perms.organizer.change_tag %}
        <li>
            <a href="{{ tag.get_update_url }}"
            class="button">
                Edit Tag</a></li>
        {% endif %}
        {% if perms.organizer.delete_tag %}
        <li>
            <a href="{{ tag.get_delete_url }}"
            class="button">
                Delete Tag
            </a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
        <p>
            Tag is associated with
            {{ tag.startup_set.count }}
            startup{{ tag.startup_set.count|pluralize }}.
        </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li>
              <a href="{{ startup.get_absolute_url }}">
                  {{ startup.name }}
              </a>
          </li>
          {% endfor %}
      </ul>
    </section>
    {% endif %}

    {% if perms.blog.view_future_post %}
        {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="{{ post.get_absolute_url }}">
                  {{ post.title|title }}
              </a></li>
              {% endfor %}
          </ul>
        </section>
        {% endif %}
         {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content</p>
        {% endif %}
    {% else %}
        {% if tag.published_posts|length > 0 %}
        <section>
            <h3>Blog Post{{ tag.published_posts|pluralize }}</h3>
        <ul>
            {% for post in tag.published_posts %}
            <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
            </a></li>
            {% endfor %}
        </ul>
        </section>
    {% endif %}
        {% if not tag.startup_set.all and not tag.published_posts %}
            <p>This tag is not related to any content</p>
        {% endif %}
    {% endif %}
{% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
              <form
                  action="{% url 'organizer_tag_create' %}"
                  method="post">
                {% csrf_token %}
                {{ form.as_p }}

            {#    {{ form.non_field_errors }}#}
            {##}
            {#      {% for field in form %}#}
            {#      {{ field.errors }}#}
            {#      <p>#}
            {#          {{ field.label_tag }}#}
            {#          {{ field }}#}
            {#          {% if field.help_text %}#}
            {#          <span class="helptext">#}
            {#              {{ field.help_text }}#}
            {#          </span>#}
            {#          {% endif %}#}
            {#      </p>#}
            {#    {% endfor %}#}

            <button class="button-primary" type="submit">
              Create Tag</button>
         </form>
    </div>
</div>
{% endblock %}

organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ tag.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">
          Update Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block create_button %}
    {% if perms.organizer.add_tag %}
    <a href="{% url 'organizer_tag_create' %}"
    class="button button-primary">
        Create New Tag</a>
    {% endif %}
{% endblock %}

{% block org_content %}
    <h2>Tag List</h2>
    {% if perms.organizer.add_tag %}
        <div class="mobile">
            <a href="{% url 'organizer_tag_create' %}"
            class="button button-primary">
                Create New Tag</a>
        </div>
    {% endif %}
<ul>
    {% for tag in tag_list %}
    <li>
        <a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
        </a>
        {% if perms.organizer.change_tag or perms.organizer.delete_tag %}
        <ul class="inline">
            {% if perms.organizer.change_tag %}
            <li>
                <a href="{{ tag.get_update_url }}"
                   class="button">
                    Edit Tag</a></li>
            {% endif %}
            {% if perms.organizer.delete_tag %}
        <li>
            <a href="{{ tag.get_delete_url }}"
               class="button">
                Delete Tag</a></li>
            {% endif %}
        </ul>
        {% endif %}
    </li>
    {% empty %}
    <li><em>There are currently no Tags available</em></li>
    {% endfor %}
</ul>
{% endblock %}